INSERT INTO estado (fiidestado, fcnombre) VALUES (1, 'AGUASCALIENTES');
INSERT INTO estado (fiidestado, fcnombre) VALUES (2, 'BAJA CALIFORNIA');
INSERT INTO estado (fiidestado, fcnombre) VALUES (3, 'BAJA CALIFORNIA SUR');
INSERT INTO estado (fiidestado, fcnombre) VALUES (4, 'CAMPECHE');
INSERT INTO estado (fiidestado, fcnombre) VALUES (5, 'CHIAPAS');
INSERT INTO estado (fiidestado, fcnombre) VALUES (6, 'CHIHUAHUA');
INSERT INTO estado (fiidestado, fcnombre) VALUES (7, 'COAHUILA');
INSERT INTO estado (fiidestado, fcnombre) VALUES (8, 'COLIMA');
INSERT INTO estado (fiidestado, fcnombre) VALUES (9, 'DISTRITO FEDERAL');
INSERT INTO estado (fiidestado, fcnombre) VALUES (10, 'DURANGO');
INSERT INTO estado (fiidestado, fcnombre) VALUES (11, 'GUANAJUATO');
INSERT INTO estado (fiidestado, fcnombre) VALUES (12, 'GUERRERO');
INSERT INTO estado (fiidestado, fcnombre) VALUES (13, 'HIDALGO');
INSERT INTO estado (fiidestado, fcnombre) VALUES (14, 'JALISCO');
INSERT INTO estado (fiidestado, fcnombre) VALUES (15, 'ESTADO DE MÉXICO');
INSERT INTO estado (fiidestado, fcnombre) VALUES (16, 'MICHOACÁN');
INSERT INTO estado (fiidestado, fcnombre) VALUES (17, 'MORELOS');
INSERT INTO estado (fiidestado, fcnombre) VALUES (18, 'NAYARIT');
INSERT INTO estado (fiidestado, fcnombre) VALUES (19, 'NUEVO LEÓN');
INSERT INTO estado (fiidestado, fcnombre) VALUES (20, 'OAXACA');
INSERT INTO estado (fiidestado, fcnombre) VALUES (21, 'PUEBLA');
INSERT INTO estado (fiidestado, fcnombre) VALUES (22, 'QUERÉTARO');
INSERT INTO estado (fiidestado, fcnombre) VALUES (23, 'QUINTANA ROO');
INSERT INTO estado (fiidestado, fcnombre) VALUES (24, 'SAN LUIS POTOSÍ');
INSERT INTO estado (fiidestado, fcnombre) VALUES (25, 'SINALOA');
INSERT INTO estado (fiidestado, fcnombre) VALUES (26, 'SONORA');
INSERT INTO estado (fiidestado, fcnombre) VALUES (27, 'TABASCO');
INSERT INTO estado (fiidestado, fcnombre) VALUES (28, 'TAMAULIPAS');
INSERT INTO estado (fiidestado, fcnombre) VALUES (29, 'TLAXCALA');
INSERT INTO estado (fiidestado, fcnombre) VALUES (30, 'VERACRUZ');
INSERT INTO estado (fiidestado, fcnombre) VALUES (31, 'YUCATÁN');
INSERT INTO estado (fiidestado, fcnombre) VALUES (32, 'ZACATECAS');
