CREATE  SEQUENCE seq_colonia INCREMENT  BY 1
     MINVALUE 1  
     START  WITH 1;

CREATE  SEQUENCE seq_calle INCREMENT  BY 1
     MINVALUE 1  
     START  WITH 1;

CREATE  SEQUENCE seq_codigopostal INCREMENT  BY 1
     MINVALUE 1  
     START  WITH 1;

CREATE  SEQUENCE seq_direccion INCREMENT  BY 1
     MINVALUE 1  
     START  WITH 1;